const postById = (id: string) => `/api/posts/${id}`;
const storyById = (id: string) => `/api/stories/${id}`;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/auth/login',
    ADMIN_LOGIN: '/api/auth/admin/login',
    REFRESH_TOKEN: '/api/auth/refresh-token',
    REGISTER: '/api/auth/register',
    GOOGLE: '/api/auth/google',
    OTP_SEND_VERIFY_EMAIL: '/api/auth/otp/send/verify-email',
    OTP_VERIFY_EMAIL: '/api/auth/otp/verify/email',
    ME_OTP_SEND_VERIFY_EMAIL: '/api/auth/me/otp/send/verify-email',
    ME_OTP_SEND_CHANGE_USERNAME: '/api/auth/me/otp/send/change-username',
    ME_OTP_SEND_CHANGE_PHONE_NUMBER: '/api/auth/me/otp/send/change-phone-number',
    ME_OTP_VERIFY_CHANGE_USERNAME: '/api/auth/me/otp/verify/change-username',
    ME_OTP_VERIFY_CHANGE_PHONE_NUMBER: '/api/auth/me/otp/verify/change-phone-number',
    OTP_SEND_RESET_PASSWORD: '/api/auth/otp/send/reset-password',
    ME_OTP_SEND_RESET_PASSWORD: '/api/auth/me/otp/send/reset-password',
    OTP_VERIFY_PASSWORD: '/api/auth/otp/verify/password',
    ME_OTP_VERIFY_PASSWORD: '/api/auth/me/otp/verify/password',
    RESET_PASSWORD: '/api/auth/reset-password',
    LOGOUT: '/api/auth/logout',
  },
  USERS: {
    ME: '/api/users/me',
    ONLINE: '/api/users/online',
    SECURITY_ACCOUNT: '/api/users/me/security-account',
  },
  PROFILES: {
    BY_ID: (id: string) => `/api/profiles/${id}`,
    REPORT_BY_ID: (id: string) => `/api/profiles/${id}/report`,
    SEARCH: '/api/profiles/search',
    ME: '/api/profiles/me',
    ME_PAGE_INFO: '/api/profiles/me/page-info',
    ME_PAGE_INFO_VISIBILITY: '/api/profiles/me/page-info/visibility',
  },
  POSTS: {
    LIST: '/api/posts',
    CREATE: '/api/posts',
    BY_ID: postById,
  },
  COMMENTS: {
    BY_POST_ID: (id: string) => `/api/comments/post/${id}`,
    CREATE: '/api/comments',
  },
  SAVED_POSTS: {
    MY: '/api/saved-posts/my',
    CREATE: '/api/saved-posts',
    BY_POST_ID: (id: string) => `/api/saved-posts/${id}`,
  },
  POST_REPORTS: {
    CREATE: '/api/post-reports',
    MY: '/api/post-reports/my',
    LIST: '/api/post-reports',
    RESOLVE: (id: string) => `/api/post-reports/${id}/resolve`,
    PENDING_COUNT: '/api/post-reports/pending-count',
  },
  COMMENT_REPORTS: {
    CREATE: '/api/comment-reports',
    MY: '/api/comment-reports/my',
    LIST: '/api/comment-reports',
    RESOLVE: (id: string) => `/api/comment-reports/${id}/resolve`,
    PENDING_COUNT: '/api/comment-reports/pending-count',
  },
  STORY_REPORTS: {
    CREATE: '/api/story-reports',
    MY: '/api/story-reports/my',
    LIST: '/api/story-reports',
    RESOLVE: (id: string) => `/api/story-reports/${id}/resolve`,
    PENDING_COUNT: '/api/story-reports/pending-count',
  },
  USER_REPORTS: {
    CREATE: '/api/user-reports',
    LEGACY_CREATE: '/api/reports/users',
    JAVA_CREATE: '/api/messenger/reports/users',
    MY: '/api/user-reports/my',
    LIST: '/api/user-reports',
    RESOLVE: (id: string) => `/api/user-reports/${id}/resolve`,
    PENDING_COUNT: '/api/user-reports/pending-count',
  },
  APP_REVIEWS: {
    PUBLIC: '/api/app-reviews/public',
    SUMMARY: '/api/app-reviews/summary',
    ME: '/api/app-reviews/me',
    CREATE: '/api/app-reviews',
    UPDATE_ME: '/api/app-reviews/me',
    DELETE_ME: '/api/app-reviews/me',
    ADMIN_LIST: '/api/admin/app-reviews',
    ADMIN_VISIBILITY: (id: string) => `/api/admin/app-reviews/${id}/visibility`,
    ADMIN_DELETE: (id: string) => `/api/admin/app-reviews/${id}`,
  },
  ADMIN: {
    USERS_SEARCH: '/api/admin/users/search',
    USER_STATUS: (id: string) => `/api/admin/users/${id}/status`,
    DASHBOARD: '/api/admin/dashboard',
    AUDIT_LOGS: '/api/admin/audit-logs',
  },
  STORIES: {
    LIST: '/api/stories',
    CREATE: '/api/stories',
    BY_USER_ID: (userId: string) => `/api/stories/user/${userId}`,
    BY_ID: storyById,
    UPLOAD: '/api/stories/upload',
    VIEW: (id: string) => `${storyById(id)}/view`,
  },
  FRIENDSHIPS: {
    PENDING_REQUESTERS: '/api/friendships/pending-requesters',
    SUGGESTIONS: '/api/friendships/suggestions',
    FRIENDS_SUGGESTIONS: '/api/friends/suggestions',
    REQUESTS_RECEIVED: '/api/friendships/requests/received',
    RECEIVED: '/api/friendships/received',
    FRIENDS_REQUESTS_RECEIVED: '/api/friends/requests/received',
    REQUESTS_SENT: '/api/friendships/requests/sent',
    SENT: '/api/friendships/sent',
    FRIENDS_REQUESTS_SENT: '/api/friends/requests/sent',
    CONTACTS: '/api/friendships/contacts',
    FRIENDS_LIST: '/api/friendships/friends',
    FRIENDS_ROOT: '/api/friends',
    REQUEST: '/api/friendships/request',
    FRIENDS_REQUEST: '/api/friends/request',
    ACCEPT: '/api/friendships/accept',
    ACCEPT_BY_REQUEST_ID: (id: string) => `/api/friendships/requests/${id}/accept`,
    ACCEPT_BY_ID: (id: string) => `/api/friendships/${id}/accept`,
    REJECT: '/api/friendships/reject',
    REQUEST_BY_ID: (id: string) => `/api/friendships/requests/${id}`,
    BY_ID: (id: string) => `/api/friendships/${id}`,
    CANCEL_REQUEST: (id: string) => `/api/friendships/requests/${id}/cancel`,
    CANCEL: '/api/friendships/cancel',
    UNFRIEND: '/api/friendships/unfriend',
    FRIENDS_BY_ID: (id: string) => `/api/friendships/friends/${id}`,
    FRIEND_BY_ID: (id: string) => `/api/friends/${id}`,
    BLOCK: '/api/friendships/block',
    BLOCK_BY_ID: (id: string) => `/api/friendships/block/${id}`,
    BLOCKED_USERS: '/api/friendships/blocked-users',
    JAVA_BLOCK_BY_ID: (id: string) => `/api/messenger/friendships/block/${id}`,
    JAVA_BLOCKED_USERS: '/api/messenger/friendships/blocked-users',
    PRESENCE: '/api/friendships/presence',
  },
  NOTIFICATIONS: {
    LIST: '/api/notifications',
    MARK_READ: (id: string) => `/api/notifications/${id}/read`,
    READ_ALL: '/api/notifications/read-all',
  },
  MEDIA: {
    CLOUDINARY_SIGNATURE: '/api/media/cloudinary-signature',
  },
} as const;
