export const APP_CONFIG = {
  MAX_IMAGE_FILE_SIZE_BYTES: 8 * 1024 * 1024,
  MAX_VIDEO_FILE_SIZE_BYTES: 20 * 1024 * 1024,
  ICON_OPTIONS: ['^_^', ':)', '<3', ':D', ':P'],
  PAGE_SIZE: 2,
  MAX_VISUAL_REPLY_LEVEL: 2,
  REPLY_INDENT_PER_LEVEL_PX: 18,
  AUTO_EXPAND_ALL_FROM_LEVEL: 3,
} as const;